apiVersion: v1
kind: Service
metadata:
  name: service-app-python-v2
spec:
  type : ClusterIP
  selector:
    app: app-python-v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
