apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-python-v1
  namespace: uygulamav1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python-v1
  template:
    metadata:
      labels:
        app: app-python-v1
    spec:
      containers:
      - name: app-python-v1
        image: regaipaydogdu/web-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
