apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-python-v2
  namespace: uygulamav2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python-v2
  template:
    metadata:
      labels:
        app: app-python-v2
    spec:
      containers:
      - name: app-python-v2
        image: regaipaydogdu/web-app:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
